dotenv: .env
dependencies:
  - "smartcontractkit/chainlink-brownie-contracts@0.3.0"

compiler:
  solc:
    version: 0.8.11
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.0"
